pincode_db = {
    "110001": {
        "pincode": "110001",
        "city": "New Delhi",
        "state": "Delhi",
        "district": "Central Delhi",
    },
    "400001": {
        "pincode": "400001",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai City",
    },
    "560001": {
        "pincode": "560001",
        "city": "Bangalore",
        "state": "Karnataka",
        "district": "Bangalore Urban",
    },
    "600001": {
        "pincode": "600001",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "district": "Chennai",
    },
    "700001": {
        "pincode": "700001",
        "city": "Kolkata",
        "state": "West Bengal",
        "district": "Kolkata",
    },
    "500001": {
        "pincode": "500001",
        "city": "Hyderabad",
        "state": "Telangana",
        "district": "Hyderabad",
    },
    "411001": {
        "pincode": "411001",
        "city": "Pune",
        "state": "Maharashtra",
        "district": "Pune",
    },
    "380001": {
        "pincode": "380001",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "district": "Ahmedabad",
    },
    "302001": {
        "pincode": "302001",
        "city": "Jaipur",
        "state": "Rajasthan",
        "district": "Jaipur",
    },
    "226001": {
        "pincode": "226001",
        "city": "Lucknow",
        "state": "Uttar Pradesh",
        "district": "Lucknow",
    },
    "682001": {
        "pincode": "682001",
        "city": "Kochi",
        "state": "Kerala",
        "district": "Ernakulam",
    },
    "440001": {
        "pincode": "440001",
        "city": "Nagpur",
        "state": "Maharashtra",
        "district": "Nagpur",
    },
    "800001": {
        "pincode": "800001",
        "city": "Patna",
        "state": "Bihar",
        "district": "Patna",
    },
    "160001": {
        "pincode": "160001",
        "city": "Chandigarh",
        "state": "Chandigarh",
        "district": "Chandigarh",
    },
    "201301": {
        "pincode": "201301",
        "city": "Noida",
        "state": "Uttar Pradesh",
        "district": "Gautam Buddha Nagar",
    },
}
